### ISSUE TITLE
Settings reset when clicking on "Save" button in general settings

### ISSUE THREAD

**Issue by Buco7854** [need4swede/Portall#10]
If you click on save in the general settings (under default IP select) it will always reset the settings

The issue comes from the settings.py file where the default IP theme and custom css are set as empty string

A fix could be to set it to None instead of empty string and make sure to set some lines after theme only if it was actually provided.

**Comment by need4swede** [comment]
This should be fixed in the latest release.
Please let me know if you experience any issues!

**Comment by Buco7854** [comment]
Seems it is fixed thanks
