### ISSUE TITLE
TCP UDP Ports cause error

### ISSUE THREAD

**Issue by Idleite** [need4swede/Portall#11]
When using the same ports on tcp and udp when importing via docker compose or docker socket a unique error is thrown
`portall  | sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: port.ip_address, port.port_number
portall  | [SQL: INSERT INTO port (ip_address, nickname, port_number, description, "order", docker_id) VALUES (?, ?, ?, ?, ?, ?) RETURNING id]
portall  | [parameters: ('127.0.0.1', None, 6881, 'neilpang/wgcf-docker:latest', 0, None)]
portall  | (Background on this error at: https://sqlalche.me/e/20/gkpj)
portall  | INFO:werkzeug:10.10.1.207 - - [10/Jul/2024 02:53:16] "POST /import HTTP/1.1" 500 -`
to fix this i propose inclusing the /tcp or /udp in the port mapping as well as changing the port database model to be String type on the port_number column

**Comment by need4swede** [comment]
The latest release added TCP/UDP support. This should solve issues where a Docker-Compose file is imported with different port protocols. 

Note that the compose file needs to include `/tcp' or `/udp` to differentiate the two.
