### ISSUE TITLE
Port arrangement doesn't stay

### ISSUE THREAD

**Issue by Node815** [need4swede/Portall#2]
When using the Drag and Drop to re-arrange ports to your liking it sticks, (For example Numerical).  But when you add a new port mapping for a service, it reverts back to the original sort.

**Comment by need4swede** [comment]
So you re-order your ports, click the '+' to add a new port, and as soon as you do that all your ports go back to their previous order? Does this still happen if you refresh the page after re-ordering your ports?

**Comment by Node815** [comment]
Yes, re-arranging and refreshing the page does this as well.

**Comment by need4swede** [comment]
Thanks for letting me know. I'll look into that right away.

**Comment by need4swede** [comment]
@Node815 Could you try the latest release and let me know if the problem still persists?

It does include some breaking changes to the database, so I suggest starting with a fresh database as I don't have any migration logic in place at the moment.

**Comment by Node815** [comment]
I started with a fresh database and install - the arrangement now stays put and does not revert , but I do have one minor thing I noticed, the newly added port goes into position 2, then 3, then 4  regardless of the initial ordering:
**Before adding a new port:**
![image](https://github.com/need4swede/Portall/assets/20736534/68a6f84f-e7b2-43b5-a4ff-27a4efea728e)
**After adding a new port**  ( I added Port 9999)
![image](https://github.com/need4swede/Portall/assets/20736534/ca394cf2-a43e-44a6-8340-af042d800d0e)
**Adding another new port**  (I added Port 9998)
![image](https://github.com/need4swede/Portall/assets/20736534/037dc91d-9d50-4400-a656-71a3d396a330)

You can see that the position stayed for port 9999, but the newly added 9998 shifted the "Portainer" port to the right.  I can repeat this and each time, it pushes the original entries (As shown in the first screenshot) to the right after port 4001.  While this is not a showstopper necessarily, the ordering should be in the order the end user adds it who can later organize the ports as desired.
