### ISSUE TITLE
Editing Port keys off Port Number, not ID

### ISSUE THREAD

**Issue by vinaykapadia** [need4swede/Portall#8]
When editing a port, the endpoint uses the port number to pick which db row to edit. I've had it edit the wrong one because of this. Should key off row id. Or another way could be to prevent duplicates (it prevents duplicates when adding new, but you can edit a port to be the same as another).

Steps to reproduce:
1. Add a port, call it A.
2. Add a second port, call it B.
3. Edit A to have the same port as B.
4. Edit B to have another port, it will change the values for A instead.

**Comment by need4swede** [comment]
Thank you for bringing this to attention. Added it to my list of bugfixes!

**Comment by need4swede** [comment]
@vinaykapadia could you give [v1.0.3](https://github.com/need4swede/Portall/releases/tag/v1.0.3) a try and let me know if you're still experiencing issues?

You may have to start from a fresh database as there may have been some breaking changes along the way.

Thank you!

**Comment by vinaykapadia** [comment]
Will do!

**Comment by vinaykapadia** [comment]
Works great now, thanks!
