### ISSUE TITLE
[ Feature ] Support For services

### ISSUE THREAD

**Issue by Idleite** [need4swede/Portall#9]
Would you be open to changing the system to have services instead of ports and the ports would be under the service
I already i am working on an implementation of this if you would be open to it

**Comment by need4swede** [comment]
Hi @Idleite 

Thank you for the great suggestion, but I am not sure I want to go that route with this. In my view, that would steer this closer to more of a 'Dashboard', more akin to the likes of Dashy, Homarr, Heimdall, etc. Those applications already allow you to manage your services, and I suspect they're much better at doing so.

Portall is Port focused, first and foremost, with IP's/Hosts as a secondary measure.

Thank you for the suggestion!
